### ISSUE TITLE
Could cspv4-info be made into a service probe?

### ISSUE THREAD

**Issue by dmiller-nmap** [sjhilt/Nmap-NSEs#1]
Hey, Stephen, sorry I didn't have a good email address for you.

cspv4-info is a single probe-response check, which usually means it fits better as a probe and match line in nmap-service-probes. There are a few things I'd need to clear up first, though:
1. Is there a possibility of expanding this script to gather more information, whether from subsequent probes or from the response to the initial probe?
2. How much of the response is either static or predictable? In other words, can we write a decent regular expression to match the response?
3. Is the session id a useful piece of information? We don't (currently) have a way to pull integers from bytes within `-sV`, so that's the kind of thing that makes a script helpful.

Here's an example service probe that you could use to provide some feedback on these questions:

```
##############################NEXT PROBE##############################
# Probes for CSPv4 (a.k.a. AB/Ethernet)
#
Probe TCP cspv4-init q|\x01\x01\0\0\0\0\0\0\0\0\0\0\0\x04\0\x05\0\0\0\0\0\0\0\0\0\0\0\0|
rarity 9
ports 2222

softmatch cspv4 m|^\x02.......| p/CSPv4/
```

As a side note, you really should use explicit endian modifiers '<' or '>' instead of native, since Nmap runs on different architectures. I'd guess the Session ID value is little-endian, since that's native on x86.

**Comment by sjhilt** [comment]
1) I will expand the script as I learn more about the actual protocol to collect more information. 
2) The session ID is random, but one could write regex around it. 
3) The session ID is needed to communicate to the device from there on out, so it helps identify it as the CSPv4 packet 

Yes, this could be a Version probe. I need to write a few more of these so we could write probes for them as well, I will change to use the explicit modifiers here soon.
