### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alaaeelsayed** [sjhilt/Nmap-NSEs#2]
it gives me attempt to index field 'players' (a nil value) here is an example of the json string {"version":{"name":"BungeeCord 1.8","protocol":47},"players":{"max":500,"online":135},"description":"test","favicon":"data:image/png;base64"}}

**Comment by DC423** [comment]
can you run with -d and provide me full output. it should find the players fine as it says "online":135 in your output.

**Comment by sjhilt** [comment]
Issue is fixed , it has to do with the data on favicon and some of the later fields.
