### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Mepth** [sjhilt/Nmap-NSEs#7]
Initiating NSE at 22:08
NSE: Starting minecraft-info against 127.0.0.1:25565.
NSE: minecraft-info against 127.0.0.1:25565 threw an error!
/usr/bin/../share/nmap/scripts/minecraft-info.nse:46: variable 'bin' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
        /usr/bin/../share/nmap/scripts/minecraft-info.nse:46: in function </usr/bin/../share/nmap/scripts/minecraft-info.nse:44>
        (...tail calls...)

**Comment by sjhilt** [comment]
Hi, Fixed this issue just had to add to require bin 

```PORT      STATE SERVICE   REASON
25565/tcp open  minecraft syn-ack
| minecraft-info: 
|   Description: A Minecraft Server
|   Max Players: 20
|   Players Online: 0
|   Version: 1.7.10
|_  Protocol: 5
